export {
  PROJECTION_PROFILE_SCHEMA_VERSION,
  type AuthorityQualifiedJurisdictionReference,
  type CommunityDeploymentProfile,
  type CommunityRelevanceAssertion,
  type CommunityRelevanceBasis,
  type CommunityRelevanceNonClaim,
  type CommunityRelevanceReviewState,
  type DeepReadonly,
  type DeploymentView,
  type EngineProjection,
  type OutputAdapter,
  type PersonaProjection,
  type ProjectedRecordReference,
  type ProjectionAuthorityState,
  type ProjectionProfileBundle,
  type ProjectionTemporalScope,
  type ProjectionVisibility,
  type ProjectionWatchRule,
  type RegionPack,
  type RequiredCommunityRelevanceNonClaims,
  type VersionedReference,
} from "./contracts";
export {
  ProjectionValidationError,
  REQUIRED_COMMUNITY_RELEVANCE_NONCLAIMS,
  createEngineProjection,
  parseProjectionProfileBundle,
  serializeEngineProjection,
} from "./projection";
